version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_newwwwwqqqqq
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ChatAppDb  # New database name
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Mount the SQL script
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin_newwwwwqqqq
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5053:80"
    depends_on:
      - postgres
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_go_app_newwwwqqqqq
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: ChatAppDb  # Ensure this database exists
      DB_HOST: postgres
      DB_PORT: "5432"
    ports:
      - "8082:8081"
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network: