package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/valdimir-makarov/Go-backend-Engineering/Complete-Golang-Micro-Service-Project/graphql/graph/model"
)

type accountResolver struct{ server *Server }

func (r *accountResolver) Orders(ctx context.Context, obj *model.Account) ([]*model.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}
