
version: '3.9'
services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "2021:8080"
    environment:
      - PORT=8080
      
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_db
      - KAFKA_BROKER=kafka:9092 
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres-auth
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default:
    name: root_default