# version: '3.9'

# services:
#   auth-service:
#     build: .
#     container_name: auth-service
#     ports:
#       - "2021:8080" # Exposed to host as 2021, inside container it's 8080
#     environment:
#       - PORT=8080
#       - DB_HOST=postgres
#       - DB_PORT=5432
#       - DB_USER=postgres
#       - DB_PASSWORD=postgres
#       - DB_NAME=auth_db
#       - KAFKA_BROKER=kafka:9092 
#     depends_on:
#       - postgres

#   krakend:
#     image: devopsfaith/krakend
#     container_name: krakend
#     ports:
#       - "9001:9001"
#     volumes:
#     - ./krakend.json:/etc/krakend/krakend.json

#     command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
#     depends_on:
#       - auth-service

#   postgres:
#     image: postgres:16
#     container_name: postgres-auth
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=auth_db
#     ports:
#       - "5435:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
# networks:
#   default:
#     name: root_default
# volumes:
#   postgres_data:
version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-auth
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: root_default

volumes:
  postgres_data:
