// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Orders []*Order `json:"orders,omitempty"`
}

type AccountInput struct {
	Name string `json:"name"`
}

type AccountPage struct {
	Items      []*Account `json:"items"`
	TotalCount int32      `json:"totalCount"`
}

type Mutation struct {
}

type Order struct {
	ID         string            `json:"id"`
	CreateAt   string            `json:"createAt"`
	TotalPrice float64           `json:"totalPrice"`
	Products   []*OrderedProduct `json:"products,omitempty"`
}

type OrderInput struct {
	AccountID string               `json:"accountId"`
	Products  []*OrderProductInput `json:"products"`
}

type OrderProductInput struct {
	ID       string `json:"id"`
	Quantity int32  `json:"quantity"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int32   `json:"quantity"`
}

type PaginationInput struct {
	Limit  *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type ProductPage struct {
	Items      []*Product `json:"items"`
	TotalCount int32      `json:"totalCount"`
}

type Query struct {
}
