// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Jobs        []*Job  `json:"jobs"`
}

type CreateJobInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CompanyID   string `json:"companyId"`
}

type Job struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Company     *Company `json:"company"`
	DatePosted  string   `json:"datePosted"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}
