// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20250819015338_AddItemsTable")]
    partial class AddItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DogId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FemaleWeightMax")
                        .HasColumnType("integer");

                    b.Property<int>("FemaleWeightMin")
                        .HasColumnType("integer");

                    b.Property<bool>("Hypoallergenic")
                        .HasColumnType("boolean");

                    b.Property<int>("LifeMax")
                        .HasColumnType("integer");

                    b.Property<int>("LifeMin")
                        .HasColumnType("integer");

                    b.Property<int>("MaleWeightMax")
                        .HasColumnType("integer");

                    b.Property<int>("MaleWeightMin")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
